version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini
      - ./docker/timezone/${TIMEZONE}:/etc/localtime
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/timezone/${TIMEZONE}:/etc/localtime
    depends_on:
      - php
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./docker/timezone/${TIMEZONE}:/etc/localtime
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - PGTZ=${TIMEZONE}
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
      - ./docker/timezone/${TIMEZONE}:/etc/localtime
    depends_on:
      - php
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    # image: rabbitmq:alpine
    ports:
      - "15672:15672"
    hostname: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - ./docker/timezone/${TIMEZONE}:/etc/localtime
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit ${RABBITMQ_DISK_LIMIT}
    depends_on:
      - php
    restart: unless-stopped

volumes:
  postgresdata:
  redisdata:
  rabbitmqdata:
